name: Pack Assets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pack:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1


      - name: Initialize Output Directory
        run: |
          mkdir -p /tmp/output
          cp -R include/* /tmp/output
          cd scripts/pack/
          bun install
          cd ../..

      - name: Pack Assets
        run: |
          bun run scripts/pack/index.ts ./src /tmp/output/v2

      - name: Create and Init Branch
        run: |
          git switch --orphan output
          git clean -fdx
          cp -R /tmp/output/* .

      - name: Commit and Push changes
        uses: actions-js/push@master
        with:
          branch: output
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
