name: Pack Assets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pack:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1


      - name: Initialize Output
        run: |
          mkdir -p /tmp/output
          cp -R include/* /tmp/output
          cd scripts/pack/
          bun install
          bun run . ../../src /tmp/output

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1