name: Prevent Translation Changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-translation-diff:
    if: github.actor != 'figuramcbot' || !contains(github.event.pull_request.title, 'Update Base Strings')
    runs-on: ubuntu-22.04

    steps:
      - name: Calculate Fetch Depth
        run: |
          echo "FETCH_DEPTH=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Check If Base Strings Changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v 'v2/lang/en_us.json')
          if [[ ! -z "$CHANGED_FILES" ]]; then
            echo "BASE_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: env.BASE_CHANGED == 'true'
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "figuramcbot"
          body-includes: "Base Strings Modified"

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1
        if: env.BASE_CHANGED == 'true' && steps.fc.outputs.comment-id == ''
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # ⚠️ Base Strings Modified ⚠️

            **Your pull request includes changes to the `en_us.json` strings file.**
            Please do not modify the base strings directly within this repository. Instead, make your changes in the [FiguraMC/Figura](https://github.com/FiguraMC/Figura) repository and submit a new pull request there.
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Fail Workflow
        if: env.BASE_CHANGED == 'true' && steps.fc.outputs.comment-id == ''
        run: exit 1